### ISSUE TITLE
Adding Travis CI for a automated Markdown to PDF conversion 

### ISSUE THREAD

**Issue by BavariaBlue** [BavariaBlue/samm#15]
We need an automated / CI markdown to PDF conversion of the file SAMM-v1.5.1.md located in
SAMM/Supporting\ Resources/v1.5/MarkDown/

The PDF file should be saved either in a new branch gh-pages or in the same directory as the .md file 

We use Travis CI because github.com/polybassa/AutomotiveScapyUtils is our parent repo.

Every time someone commits to the origin, the process should start.

@polybassa Below are some local conversion guidelines.

I set up the local conversion from Markdown to PDF like this (Mac OS):
1. Install Pandoc
1.1. Windows
https://github.com/jgm/pandoc/releases/tag/2.7.3
**1.2. Mac
brew install pandoc**
1.3 Linux
https://github.com/jgm/pandoc/releases/tag/2.7.3

2. Install Latex Environment
2.1. Windows: 
https://miktex.org/
**2.2. Mac
Tinytex
curl -sL "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh
tlmgr install collection-fontsrecommended**
2.3. Linux
apt-get install texlive

3. Compile PDF with Pandoc and environmental Latex (with **MacOS**)
3.1. cd into the MarkDown path 
e.g. 
$ cd SAMM/Supporting\ Resources/v1.5/MarkDown/
3.2. Call the pandoc method to convert .md into .pdf
$ pandoc SAMM-1.5.1.md -s -o SAMM-1.5.1.pdf

-----
I ran into several package and font missing errors because of the usage of the tinyTex solution.
I installed the required LaTex packages via 
$ tlmgr search --global --file "/missingPackage.sty"
psnfss:
        texmf-dist/tex/latex/psnfss/times.sty
...

$ tlmgr install psnfss
....

There was a problem with Unicode symbols, so I set the parameter 
"--pdf-engine=xelatex"
Thus having:
$ pandoc SAMM-1.5.1.md --pdf-engine=xelatex  -s -o SAMM-1.5.1.pdf

**Comment by polybassa** [comment]
I've added the CI file: https://github.com/polybassa/AutomotiveScapyUtils/commit/0a2d5a435dca7f5146837dc7644b0aae66f7e2ad

**Comment by polybassa** [comment]
Hi, the SAMM document is now generated automatically. https://github.com/polybassa/AutomotiveScapyUtils/releases 
The only thing you need to do now, keep the git submodule up to date to the state of this repo you want to build.
